name: parkowa_nie
description: A hammer of invalid parking.

publish_to: "none"
version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_analytics: "^7.1.1"
  firebase_core: "^1.0.3"
  flutter_mailer: ^1.0.0
  geocoding: ^2.0.0
  geolocator: ^7.0.1
  hive_flutter: ^1.0.0
  hive: ^2.0.2
  http: ^0.13.1
  i18n_extension: ^3.0.0
  image_gallery_saver: "^1.6.9"
  image_picker: ^0.7.4
  intl: ^0.17.0
  path_provider: ^2.0.1
  photo_view: ^0.11.1
  provider: ^5.0.0
  slugify: ^2.0.0
  syncfusion_flutter_charts: ^19.2.60

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  flutter_launcher_icons: "^0.9.0"
  hive_generator: ^1.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/cities.json
