name: parkowa_nie
description: A hammer of invalid parking.

publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  i18n_extension: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_mailer: ^1.0.0
  geolocator: ^7.0.1
  geocoding: ^2.0.0
  image_picker: ^0.7.4
  provider: ^5.0.0
  path_provider: ^2.0.1
  intl: ^0.17.0
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  slugify: ^2.0.0
  firebase_core: "^1.0.3"
  firebase_analytics: "^7.1.1"
  image_gallery_saver: "^1.6.9"
  photo_view: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner: ^1.12.2
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
