class OffenceType {
  static const NO_PARKING_ZONE = 'NO_PARKING_ZONE';
  static const NO_ENOUGH_SIDEWALK_SPACE = 'NO_ENOUGH_SIDEWALK_SPACE';
  static const TOO_CLOSE_TO_CROSSING = 'TOO_CLOSE_TO_CROSSING';
  static const TOO_CLOSE_TO_INTERSECTION = 'TOO_CLOSE_TO_INTERSECTION';
  static const NO_STOPPING_SING = 'NO_STOPPING_SIGN';
}

const OFFENCES = [
  OffenceType.NO_PARKING_ZONE,
  OffenceType.NO_ENOUGH_SIDEWALK_SPACE,
  OffenceType.TOO_CLOSE_TO_CROSSING,
  OffenceType.TOO_CLOSE_TO_INTERSECTION,
  OffenceType.NO_STOPPING_SING,
];
