class OffenceType {
  static const NO_PARKING_ZONE = 'NO_PARKING_ZONE';
  static const NO_ENOUGH_SIDEWALK_SPACE = 'NO_ENOUGH_SIDEWALK_SPACE';
  static const TOO_CLOSE_TO_CROSSING_INTERSECTION =
      'TOO_CLOSE_TO_CROSSING_INTERSECTION';
}
